version: "3.5"

networks:
  transcendence-network:

services:
  front:
    container_name: front
    depends_on:
      - back
    build:
      context: ./client
      args:
       - ARG_VITE_URL_API=${URL}
    ports:
      - "80:80"
    networks:
      - transcendence-network
    restart: always
  back:
    container_name: back
    networks:
      - transcendence-network
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./server
      args:
       - ARG_VITE_URL_API=${URL}
       - ARG_FORTYTWO_CLIENT_ID=${FORTYTWO_CLIENT_ID}
       - ARG_FORTYTWO_CLIENT_SECRET=${FORTYTWO_CLIENT_SECRET}
       - ARG_JWT_SECRET=${JWT_SECRET}
       - ARG_TWO_FACTOR_AUTHENTICATION_APP_NAME=${TWO_FACTOR_AUTHENTICATION_APP_NAME}
       - ARG_USER=${USER}
       - ARG_PASSWORD=${PASSWORD}
       - ARG_DBNAME=${DBNAME}
    ports:
      - "6000:6000"
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
    restart: always
  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: db
    build:
      context: ./db
      args:
       - ARG_USER=${USER}
       - ARG_PASSWORD=${PASSWORD}
       - ARG_DBNAME=${DBNAME}
    ports:
      - "5432:5432"
    networks:
      - transcendence-network
    restart: always