version: "3.5"

services:
  front:
    container_name: front
    depends_on:
      - back
    build:
      context: ./client
      args:
       - ARG_URL=${URL}
    ports:
      - "5999:5999"
    restart: unless-stopped
  back:
    container_name: back
    depends_on:
      - db
    build:
      context: ./server
      args:
       - URL=${URL}
    ports:
      - "6000:6000"
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "4001:4001"
    restart: unless-stopped
  db:
    container_name: db
    build:
      context: ./db
      args:
       - ARG_USER=${USER}
       - ARG_PASSWORD=${PASSWORD}
       - ARG_DBNAME=${DBNAME}
       - ARG_FORTYTWO_CLIENT_ID=${FORTYTWO_CLIENT_ID}
       - ARG_FORTYTWO_CLIENT_SECRET=${FORTYTWO_CLIENT_SECRET}
       - ARG_JWT_SECRET=${JWT_SECRET}
       - ARG_TWO_FACTOR_AUTHENTICATION_APP_NAME=${TWO_FACTOR_AUTHENTICATION_APP_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped